# Generated by Django 5.1 on 2025-08-19 19:42

import app.models
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.country'),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, default=app.models.Language.get_english, to='app.language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('0', 'Unknown'), ('1', 'African'), ('2', 'Native American'), ('3', 'Asian or Pacific Islander'), ('4', 'Hispanic'), ('5', 'Caucasian'), ('6', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='joint_title',
            field=models.CharField(blank=True, choices=[('1LM', '1st Lt. and Mrs.'), ('1LT', '1st Lt.'), ('ATM', 'Atty. and Mrs.'), ('ATT', 'Atty.'), ('B/M', 'Bro. and Mrs.'), ('BR', 'Brother'), ('C/C', 'Chaplain and Chaplain'), ('C/D', 'Chaplain and Dr.'), ('C/M', 'Captain and Mrs.'), ('CAP', 'Captain'), ('CH', 'Chaplain'), ('CHP', 'Chaplain and Mrs.'), ('CLL', 'Col.'), ('COL', 'Col. and Mrs.'), ('D/D', 'Dr. and Dr.'), ('D/M', 'Dr. and Mrs.'), ('D/R', 'Dr. and Rev.'), ('DR', 'Dr.'), ('DRS', 'Drs.'), ('E/M', 'Ensign and Mrs.'), ('H/M', 'Hon. and Mrs.'), ('HON', 'Hon.'), ('J/M', 'Judge and Mrs.'), ('L/T', 'Lt. Col.'), ('LC', 'Lt. Com.'), ('LCM', 'Lt. Com. and Mrs.'), ('LT', 'Lt.'), ('LTC', 'Lt. Col. and Mrs.'), ('LTM', 'Lt. and Mrs.'), ('M/C', 'Mr. and Chaplain'), ('M/D', 'Mr. and Dr.'), ('M/M', 'Mr. and Mrs.'), ('M/R', 'Mr. and Rev.'), ('MAJ', 'Major'), ('MAM', 'Major and Mrs.'), ('MIN', 'Minister'), ('MIS', 'Miss'), ('MNM', 'Minister and Mrs.'), ('MR', 'Mr.'), ('MRD', 'Mr. and Rev. Dr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MSG', 'MSgt.'), ('MSM', 'MSgt. and Mrs.'), ('P/M', 'Prof. and Mrs.'), ('P/P', 'Profs.'), ('P/S', 'Pastor and Sister'), ('PAD', 'Pastor and Dr.'), ('PAM', 'Pastor and Mrs.'), ('PAS', 'Pastor'), ('PRF', 'Prof.'), ('R/C', 'Rev. and Chaplain'), ('R/D', 'Rev. and Dr.'), ('R/R', 'Rev. and Rev.'), ('RAB', 'Rabbi'), ('RDD', 'Rev. Dr. and Dr.'), ('RDM', 'Rev. Dr. and Mrs.'), ('RDR', 'Rev. Dr.'), ('RE', 'Rev.'), ('REV', 'Rev. and Mrs.'), ('S/M', 'Sgt. and Mrs.'), ('SGM', 'SSgt. and Mrs.'), ('SGT', 'Sgt.'), ('SIS', 'Sister'), ('SMM', 'Sgt. Major and Mrs.'), ('SSG', 'SSgt.'), ('TSG', 'TSGT'), ('TSM', 'TSGT and Mrs.')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced or Separated'), ('W', 'Widowed')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, choices=[('1LT', '1st Lt.'), ('ATT', 'Attorney'), ('BR', 'Brother'), ('CAP', 'Captain'), ('CHP', 'Chaplain'), ('COL', 'Col.'), ('DR', 'Dr.'), ('ENS', 'Ensign'), ('HON', 'Hon.'), ('JU', 'Judge'), ('LC', 'Lt. Com.'), ('LT', 'Lt.'), ('LTC', 'Lt. Col.'), ('MAJ', 'Major'), ('MIN', 'Minister'), ('MIS', 'Miss'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MSG', 'MSgt.'), ('PAS', 'Pastor'), ('PRF', 'Prof.'), ('PRO', 'Prof.'), ('RAB', 'Rabbi'), ('RDR', 'Rev. Dr.'), ('REV', 'Rev.'), ('SGT', 'Sgt.'), ('SIS', 'Sister'), ('SM', 'Sgt. Major'), ('SSG', 'SSgt,'), ('TSG', 'TSGT')], max_length=3, null=True),
        ),
    ]
