# Generated by Django 5.1 on 2025-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_grade_course_alter_grade_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='files', to='app.course'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='files', to='app.learningobjective'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='files', to='app.coursetemplate'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
