# Generated by Django 5.1 on 2025-09-04 16:16

from django.db import migrations

def fk2mm(apps, schema_editor):
    SharedFile = apps.get_model('app', 'SharedFile')
    for sf in SharedFile.objects.all():
        sf.templates.add(sf.course)
        sf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sharedfile_courses_sharedfile_objectives_and_more'),
    ]

    operations = [
        migrations.RunPython(fk2mm),
    ]
