# Generated by Django 5.1 on 2025-09-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250904_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='course',
        ),
    ]
