# Generated by Django 5.1 on 2025-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sharedfile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementaward',
            name='home_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home State/Country'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
