# Generated by Django 5.1 on 2025-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_achievementaward_home_state_prospect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffrecord',
            name='acceptance_date',
            field=models.DateField(blank=True, help_text='Date welcome letter was sent (set automatically)', null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='acceptance_date',
            field=models.DateField(blank=True, help_text='Set automatically when welcome letter is sent.', null=True),
        ),
    ]
