# Generated by Django 5.1 on 2025-10-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coursetemplate_repeatable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerfees',
            options={'verbose_name_plural': 'Center fees'},
        ),
        migrations.CreateModel(
            name='FeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
