# Generated by Django 5.1 on 2025-10-31 17:08

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_centerfees_options_feehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feehistory',
            options={'verbose_name_plural': 'Fee history'},
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='language',
            field=models.ForeignKey(default=app.models.Language.get_english_single, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.language'),
        ),
        migrations.AlterField(
            model_name='feehistory',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='beginning of last AY in which this fee applies, e.g. "2012" for superseded in AY13-14', null=True),
        ),
        migrations.AlterField(
            model_name='feehistory',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='beginning of first AY in which this fee applies, e.g. "2020" for AY20-21 onwards', null=True),
        ),
    ]
