# Generated by Django 5.1 on 2026-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_feehistory_options_sharedfile_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
